In [1]:
1+1

2

In [8]:
import pickle

In [9]:
with open('test_data.pkl', 'rb') as f:
    data = pickle.load(f)

In [10]:
data

{'data': array([[5.8, 4. , 1.2, 0.2],
        [5.1, 2.5, 3. , 1.1],
        [6.6, 3. , 4.4, 1.4],
        [5.4, 3.9, 1.3, 0.4],
        [7.9, 3.8, 6.4, 2. ],
        [6.3, 3.3, 4.7, 1.6],
        [6.9, 3.1, 5.1, 2.3],
        [5.1, 3.8, 1.9, 0.4],
        [4.7, 3.2, 1.6, 0.2],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.7, 4.2, 1.3],
        [5.4, 3.9, 1.7, 0.4],
        [7.1, 3. , 5.9, 2.1],
        [6.4, 3.2, 4.5, 1.5],
        [6. , 2.9, 4.5, 1.5],
        [4.4, 3.2, 1.3, 0.2],
        [5.8, 2.6, 4. , 1.2],
        [5.6, 3. , 4.5, 1.5],
        [5.4, 3.4, 1.5, 0.4],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 2.6, 4.4, 1.2],
        [5.4, 3. , 4.5, 1.5],
        [6.7, 3. , 5. , 1.7],
        [5. , 3.5, 1.3, 0.3],
        [7.2, 3.2, 6. , 1.8],
        [5.7, 2.8, 4.1, 1.3],
        [5.5, 4.2, 1.4, 0.2],
        [5.1, 3.8, 1.5, 0.3],
        [6.1, 2.8, 4.7, 1.2],
        [6.3, 2.5, 5. , 1.9]]),
 'labels': array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
      

In [11]:
type(data['data'])

numpy.ndarray

In [13]:
X_test = data['data']

In [14]:
X_test[0:10].sum()

141.70000000000002

In [11]:
with open('clr1.pkl', 'rb') as f:
    clr1 = pickle.load(f)

In [12]:
clr1

RandomForestClassifier()

In [13]:
type(clr1)

sklearn.ensemble._forest.RandomForestClassifier

In [14]:
vars(clr1)

{'base_estimator': DecisionTreeClassifier(),
 'n_estimators': 100,
 'estimator_params': ('criterion',
  'max_depth',
  'min_samples_split',
  'min_samples_leaf',
  'min_weight_fraction_leaf',
  'max_features',
  'max_leaf_nodes',
  'min_impurity_decrease',
  'random_state',
  'ccp_alpha'),
 'bootstrap': True,
 'oob_score': False,
 'n_jobs': None,
 'random_state': None,
 'verbose': 0,
 'warm_start': False,
 'class_weight': None,
 'max_samples': None,
 'criterion': 'gini',
 'max_depth': None,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'min_weight_fraction_leaf': 0.0,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'ccp_alpha': 0.0,
 'n_features_in_': 4,
 'n_outputs_': 1,
 'classes_': array([0, 1, 2]),
 'n_classes_': 3,
 'base_estimator_': DecisionTreeClassifier(),
 'estimators_': [DecisionTreeClassifier(max_features='auto', random_state=1939243435),
  DecisionTreeClassifier(max_features='auto', random_state=831208608),
  DecisionTreeClassifier(max

In [15]:
clr1.predict_proba(X_test)

array([[0.96, 0.04, 0.  ],
       [0.  , 0.98, 0.02],
       [0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.01, 0.99],
       [0.  , 0.91, 0.09],
       [0.  , 0.04, 0.96],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.99, 0.01],
       [1.  , 0.  , 0.  ],
       [0.  , 0.98, 0.02],
       [0.  , 0.99, 0.01],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.97, 0.03],
       [0.05, 0.87, 0.08],
       [0.  , 0.05, 0.95],
       [1.  , 0.  , 0.  ],
       [0.  , 0.05, 0.95],
       [0.  , 1.  , 0.  ],
       [0.98, 0.02, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.07, 0.93]])

In [16]:
clr1.predict(X_test)

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

In [17]:
X_test.dtype

dtype('float64')

In [18]:
X_test.shape

(30, 4)

In [16]:
# ! python3 -m pip install onnxruntime

In [3]:
import onnxruntime as rt

In [4]:
sess = rt.InferenceSession("rf_iris.onnx", providers=["CPUExecutionProvider"])

In [15]:
X_test.dtype

dtype('float64')

In [17]:
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
prob_name = sess.get_outputs()[1].name

In [18]:
input_name, label_name, prob_name

('float_input', 'output_label', 'output_probability')

In [19]:
pred_onx = sess.run([label_name], {input_name: X_test})[0]

In [20]:
pred_onx

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2], dtype=int64)

In [21]:
pred_onx_prob = sess.run([prob_name], {input_name: X_test})[0]

In [22]:
pred_onx_prob

[{0: 0.9599999785423279, 1: 0.03999999910593033, 2: 0.0},
 {0: 0.009999999776482582, 1: 0.9799999594688416, 2: 0.009999999776482582},
 {0: 0.0, 1: 1.0, 2: 0.0},
 {0: 1.0, 1: 0.0, 2: 0.0},
 {0: 0.0, 1: 0.029999999329447746, 2: 0.9699999690055847},
 {0: 0.0, 1: 0.8799999952316284, 2: 0.11999999731779099},
 {0: 0.0, 1: 0.009999999776482582, 2: 0.9899999499320984},
 {0: 1.0, 1: 0.0, 2: 0.0},
 {0: 1.0, 1: 0.0, 2: 0.0},
 {0: 0.0, 1: 0.009999999776482582, 2: 0.9899999499320984},
 {0: 0.0, 1: 1.0, 2: 0.0},
 {0: 1.0, 1: 0.0, 2: 0.0},
 {0: 0.0, 1: 0.0, 2: 1.0},
 {0: 0.0, 1: 0.9799999594688416, 2: 0.019999999552965164},
 {0: 0.0, 1: 0.9899999499320984, 2: 0.009999999776482582},
 {0: 1.0, 1: 0.0, 2: 0.0},
 {0: 0.0, 1: 1.0, 2: 0.0},
 {0: 0.0, 1: 0.9899999499320984, 2: 0.009999999776482582},
 {0: 0.9899999499320984, 1: 0.009999999776482582, 2: 0.0},
 {0: 1.0, 1: 0.0, 2: 0.0},
 {0: 0.0, 1: 0.9899999499320984, 2: 0.009999999776482582},
 {0: 0.03999999910593033, 1: 0.8700000047683716, 2: 0.089999996125